### ISSUE TITLE
图片附近的空白较大

### ISSUE THREAD

**Issue by telepathphd** [endaytrer/xjtupurple#8]
图片附近的空白较大，尝试过从网页版到iOS中微信打开，相对于原版还是过大，比较明显，希望能够一致。

**Comment by endaytrer** [comment]
我使用的iPhone SE观感是还可以的:
![IMG_0406(20200830-113045)](https://user-images.githubusercontent.com/49216312/91650754-f8a89780-eab5-11ea-986e-1911b97f5258.PNG)
![IMG_0409](https://user-images.githubusercontent.com/49216312/91650757-fb0af180-eab5-11ea-9ab1-79727498d1e6.PNG)
我还是先改小了1个px, 如果你能提供截图什么的话我会继续改进.

**Comment by telepathphd** [comment]
我是iphone xr，用企业版微信打开两个网站，分别如图：
![665DA5C8-15A2-4153-99B4-3D63F4269B0E](https://user-images.githubusercontent.com/44917778/91652057-27c70500-eac6-11ea-9f48-44ed2786d491.jpeg)

![Uploading 48D7D2EA-7340-4A3A-AE20-479DC0E9B3C7.jpeg…]()
可以看出差别

**Comment by endaytrer** [comment]
现在我在交大校园码菜单里加了调节图片宽度的选项, 可以根据原来显示的样式自行调节, 并保存到缓存中
