### ISSUE TITLE
感谢作者伟大的工作，另:https://xjtupurple.codes/链接已失效

### ISSUE THREAD

**Issue by bailingnan** [endaytrer/xjtupurple#9]

**Comment by endaytrer** [comment]
现在我已经把xjtupurple.codes解析到备用服务器了, 原有的github pages好像不能起作用了. 现在无法通过https访问, http://xjtupurple.codes应该是可以的.

**Comment by optomao** [comment]
> 
> 
> 现在我已经把xjtupurple.codes解析到备用服务器了, 原有的github pages好像不能起作用了. 现在无法通过https访问, http://xjtupurple.codes/ 应该是可以的.

移动4G无法打开，教育网出口可以。难过。

**Comment by endaytrer** [comment]
很抱歉没有办法, 除非在墙内购买服务器并且申请公网IP. 服务器架在墙外, 移动墙上加墙.

**Comment by endaytrer** [comment]
由于hello.xjtu.edu.cn是http的, 使用https去请求照片会导致不安全而某些浏览器无法访问; 加之微信好像屏蔽了所有的Netlify网页, Github Pages无法完成请求照片的功能, 唯一的解决办法是架在墙外的服务器上, 且不开放https协议. 这个Issue暂时先close了.
